# To make it easier to self-host, we have a preset docker compose config that also
# has a container with a Postgres instance running.
# You can tweak around this file to match your instances

version: "3.7"

services:
  # This service runs the backend app in the port 3170
  hoppscotch-backend:
    image: gaozhidf/hoppscotch-backend:20230401
    container_name: hoppscotch-backend
    env_file:
      - ./.env
    restart: always
    environment:
      # Edit the below line to match your PostgresDB URL if you have an outside DB (make sure to update the .env file as well)
      - DATABASE_URL=postgresql://postgres:testpass@hoppscotch-db:5432/hoppscotch?connect_timeout=300
      - MAILER_SMTP_URL=smtp://hoppscotch-mailserver:1025
      # - MAILER_SMTP_URL=smtps://hoppscotch@hoppscotch-mailserver:testpass@hoppscotch-mailserver:1025
      - PORT=3000
    depends_on:
      - hoppscotch-db
    ports:
      - "3170:3000"

  # The main hoppscotch app. This will be hosted at port 3000
  # NOTE: To do TLS or play around with how the app is hosted, you can look into the Caddyfile for
  #       the SH admin dashboard server at packages/hoppscotch-selfhost-web/Caddyfile
  hoppscotch-app:
    image: gaozhidf/hoppscotch-app:20230401
    container_name: hoppscotch-app
    env_file:
      - ./.env
    depends_on:
      - hoppscotch-backend
    ports:
      - "3000:8080"

  # The Self Host dashboard for managing the app. This will be hosted at port 3100
  # NOTE: To do TLS or play around with how the app is hosted, you can look into the Caddyfile for
  #       the SH admin dashboard server at packages/hoppscotch-sh-admin/Caddyfile
  hoppscotch-sh-admin:
    image: gaozhidf/hoppscotch-sh-admin:20230401
    container_name: hoppscotch-sh-admin
    env_file:
      - ./.env
    depends_on:
      - hoppscotch-backend
    ports:
      - "3100:8080"

  # The preset DB service, you can delete/comment the below lines if
  # you are using an external postgres instance
  # This will be exposed at port 5432
  hoppscotch-db:
    image: gaozhidf/hoppscotch-db:20230401
    container_name: hoppscotch-db
    ports:
      - "5432:5432"
    environment:
      # NOTE: Please UPDATE THIS PASSWORD!
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: hoppscotch
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data

  hoppscotch-mailserver:
    image: dockage/mailcatcher:0.8.2
    container_name: hoppscotch-mailserver
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      # NOTE: Please UPDATE THIS PASSWORD!
      EMAIL_HOST_PASSWORD: testpass
      EMAIL_HOST_USER: hoppscotch
